### ISSUE TITLE
description.tex 

### ISSUE THREAD

**Issue by amjokisaari** [usnistgov/phasefield-precipitate-aging#6]
Documentation in the readme says to build your description via "pdflatex description.tex", but that's the not the name of the file.  

More importantly, *description.tex seems to have an error in the equations in section 1 describing the free energy density (after eq. 3).  
[phasefield-precipitate-aging_description.pdf](https://github.com/usnistgov/phasefield-precipitate-aging/files/1325517/phasefield-precipitate-aging_description.pdf)

**Comment by amjokisaari** [comment]
Also, are you actually doing the tanh formulation, or have you removed that? (Section 2.2)

**Comment by tkphd** [comment]
Wow, this document is way out of date. Will spend some time overhauling for the improved (faster) formulation.

**Comment by tkphd** [comment]
Way, *way* out of date.
Making a refactoring effort this week, which will simplify documenting the "current" code.

**Comment by tkphd** [comment]
Fixed, in the worst possible way, by bd968ee63a4c612f56e8da02e473581b3c8270a3.
In the process of Doxygenating the streamlined codebase. It's getting easier to explain by the day!
